import java.sql.*;
import java.sql.DriverManager;

import javax.swing.JOptionPane;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * misc.java
 *
 * Created on 25 Oct, 2015, 5:30:39 PM
 */

/**
 *
 * @author Owner
 */
public class misc extends javax.swing.JFrame {
String io="",io1="",io2="",io3="",io4="",io5="",aa="";
int re=0,re1=0;
    /** Creates new form misc */
    public misc() {
        initComponents();
    }
    public misc(String a,String o,String o1,String o2,String o3, String o4, String o5,int kj, int kj1) {
       
        aa=a;
        re=kj;
        re1=kj1;
        io=o;
        io1=o1;
        io2=o2;
        io3=o3;
        io4=o4;
        io5=o5;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrb1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jrb5 = new javax.swing.JRadioButton();
        jrb3 = new javax.swing.JRadioButton();
        jrb2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrb4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        el2 = new javax.swing.JLabel();
        el1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jrb1);
        jrb1.setFont(new java.awt.Font("Andalus", 0, 18));
        jrb1.setText("Bridal suite");

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SPECIAL ROOMS");

        buttonGroup1.add(jrb5);
        jrb5.setFont(new java.awt.Font("Andalus", 0, 18));
        jrb5.setText("Family room");

        buttonGroup1.add(jrb3);
        jrb3.setFont(new java.awt.Font("Andalus", 0, 18));
        jrb3.setText("VIP room");

        buttonGroup1.add(jrb2);
        jrb2.setFont(new java.awt.Font("Andalus", 0, 18));
        jrb2.setText("Soundproof room");

        jLabel2.setText("(max 3 people)");

        jLabel3.setText("(max 2 people)");

        jLabel4.setText("(max 3 people)");

        buttonGroup1.add(jrb4);
        jrb4.setFont(new java.awt.Font("Andalus", 0, 18));
        jrb4.setText("Room for disabled guest");

        jLabel5.setText("(max 2 people)");

        jLabel6.setText("(max 6 people)");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("CHECK AVAILABILITY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Andalus", 0, 18));
        jLabel10.setText("No.of rooms available");

        jLabel11.setFont(new java.awt.Font("Andalus", 0, 18));
        jLabel11.setText("Price per room");

        el2.setFont(new java.awt.Font("Andalus", 0, 18));

        el1.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("PROCEED");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2))
                            .addComponent(jrb5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jrb3)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb2)
                            .addComponent(jrb4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(el2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(el1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jButton4))
                            .addComponent(jLabel6))
                        .addGap(77, 77, 77)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(486, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb2)
                            .addComponent(jrb1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb3)
                            .addComponent(jrb4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb5)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(el1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(el2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
bookroom e = new bookroom();
this.setVisible(false);
e.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String y = jrb1.getText();
 String t = jrb2.getText();
 String u = jrb3.getText();
 String i = jrb4.getText();
 String l = jrb5.getText();
 String h = "unbooked";

 if (jrb1.isSelected())
{
     try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT count(*) from room where type_of_room ='"+y+"' and statuus ='"+h+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  int e = rs.getInt("count(*)");
 el1.setText(""+e);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
      try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price_per_day from hotel where type_of_room ='"+y+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  int e2 = rs.getInt("price_per_day");
 el2.setText(""+e2);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
}
 if (jrb2.isSelected())
{
     try{
Class.forName("java.sql.Driver");
Connection co = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = co.createStatement() ;
String quer = "SELECT count(*) from room where type_of_room ='"+t+"' and statuus ='"+h+"';";
ResultSet s = stmt.executeQuery(quer) ;
s.first();
  int n = s.getInt("count(*)");
 el1.setText(""+n);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price_per_day from hotel where type_of_room ='"+t+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  int e1 = rs.getInt("price_per_day");
 el2.setText(""+e1);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
}
 if (jrb3.isSelected())
{
     try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT count(*) from room where type_of_room ='"+u+"' and statuus ='"+h+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  int g = rs.getInt("count(*)");
 el1.setText(""+g);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
   try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price_per_day from hotel where type_of_room ='"+u+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  int e3 = rs.getInt("price_per_day");
 el2.setText(""+e3);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
}
 if (jrb4.isSelected())
{
     try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT count(*) from room where type_of_room ='"+i+"' and statuus ='"+h+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  int f = rs.getInt("count(*)");
 el1.setText(""+f);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price_per_day from hotel where type_of_room ='"+i+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  int e4 = rs.getInt("price_per_day");
 el2.setText(""+e4);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
}
 if (jrb5.isSelected())
{
     try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT count(*) from room where type_of_room ='"+l+"' and statuus ='"+h+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  int a = rs.getInt("count(*)");
 el1.setText(""+a);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price_per_day from hotel where type_of_room ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  int e5 = rs.getInt("price_per_day");
 el2.setText(""+e5);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 
}       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if(jrb1.isSelected()==true)
            aa=jrb1.getText();
            if(jrb2.isSelected()==true)
               aa=jrb2.getText();
            if(jrb3.isSelected()==true)
               aa=jrb3.getText();
            if(jrb4.isSelected()==true)
                 aa=jrb4.getText();
            if(jrb5.isSelected()==true)
                aa=jrb5.getText();
int e5=0;
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT max_accomodation from hotel where type_of_room ='"+aa+"';";
ResultSet rs = stmt.executeQuery(query);
rs.first();
  e5 = rs.getInt("max_accomodation");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }

int ks=Integer.parseInt(el1.getText());
if(ks==0)
{
    JOptionPane.showMessageDialog(null,"no rooms available of this type" +
            "please select another type of room");
}
else
        if(re > e5 || re1 > 1)
        {
         JOptionPane.showMessageDialog(null,"max " +e5+ " adults and 1 child can be accomodated in a room");
        }
        else
        {
    showroom a = new showroom(aa,io,io1,io2,io3,io4,io5);
this.setVisible(false);
a.setVisible(true);
        }

        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new misc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel el1;
    private javax.swing.JLabel el2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JRadioButton jrb3;
    private javax.swing.JRadioButton jrb4;
    private javax.swing.JRadioButton jrb5;
    // End of variables declaration//GEN-END:variables

}
