import java.sql.*;
import java.sql.DriverManager;
import javax.swing.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * payment.java
 *
 * Created on 26 Oct, 2015, 12:44:49 AM
 */

/**
 *
 * @author Owner*/
public class payment extends javax.swing.JFrame {
String a5="",q1="",q2="",q3="",q4="",q5="",q6="",q7="",q8="",q9="",q10="";
int q11=0;
    /** Creates new form payment */
    public payment() {
        initComponents();
    }
    public payment(String a,String b,String c,String a4,String u1,String u2,String u3,String u4,String u5,String u6,String u7,int f) {
        a5=a4;
        q1=u1;
        q2=u2;
        q3=u3;
        q4=u4;
        q5=u5;
        q6=u6;
        q7=u7;
        q10=c;
        q11=f;
        q8=a;
        q9=b;
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        gf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PAYMENT");

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel2.setText("Card No.");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12));

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel3.setText("Card Holder");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12));

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel4.setText("Pay To");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12));
        jLabel5.setText("Aanchal1998");

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel6.setText("Pay ");

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel7.setText("Rs.");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setText("BOOK ROOM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jButton1)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(gf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int e6=0;
String jl="unbooked";
String yu="booked";
int customercode1 = 0;
int customercode2 = 0;
int customercode3 = 0;
int customercode = 0;
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "select max(customer_code) from customer;";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
customercode1 = rs.getInt("max(customer_code)");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "select max(customer_code) from cancellation;";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
customercode2 = rs.getInt("max(customer_code)");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "select max(customer_code) from left_customer;";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
customercode3 = rs.getInt("max(customer_code)");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
int cc2 = 0;
if(customercode1>customercode2)
{
    if(customercode1>customercode3)
    { cc2 = customercode1 + 1;
}
    else
    { cc2 = customercode3 + 1;
}
}
    else{
if(customercode2>customercode3)
{
  cc2 = customercode2 + 1;
}
else
  cc2 = customercode3 + 1;
    }
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String quer = "select min(room_no) from room where type_of_room='"+a5+"' and statuus='"+jl+"';";
ResultSet s = stmt.executeQuery(quer);
s.first();
  e6 = s.getInt("min(room_no)");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
String quer = "insert into customer values('"+e6+"','"+q8+"','"+q9+"','"+q10+"','"+q3+q2+q1+"','"+q6+q5+q4+"',"+q11+",'"+q7+"','"+a5+"',"+cc2+");";
Statement stmt = con.createStatement() ;
stmt.executeUpdate(quer);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String quer = "update room set statuus='"+yu+"' where room_no='"+e6+"';";
stmt.executeUpdate(quer);
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
JOptionPane.showMessageDialog(null,"room booked! " +
        "You have been alloted room no."+e6+
        " Click OK to generate reservation slip");
reservation_slip e = new reservation_slip(cc2,e6,q10);
this.setVisible(false);
e.setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
details e = new details();
this.setVisible(false);
e.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
gf.setText(""+q11);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
