import java.sql.*;
import java.sql.DriverManager;
import javax.swing.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * showroom.java
 *
 * Created on 25 Oct, 2015, 6:06:16 PM
 */

/**
 *
 * @author Owner
 */
public class showroom extends javax.swing.JFrame {
String iio="",iio1="",iio2="",iio3="",iio4="",iio5="",aaa="";
int yy=0,yy1=0,r=0;
    /** Creates new form showroom */
    public showroom() {
        initComponents();
    }
    public showroom(String aa,String io,String io1,String io2,String io3,String io4,String io5) {
        aaa=aa;
        iio=io;
        iio1=io1;
        iio2=io2;
        iio3=io3;
        iio4=io4;
        iio5=io5;
        initComponents();
    }

    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        r1 = new javax.swing.JCheckBox();
        r3 = new javax.swing.JCheckBox();
        r2 = new javax.swing.JCheckBox();
        r4 = new javax.swing.JCheckBox();
        r5 = new javax.swing.JCheckBox();
        r6 = new javax.swing.JCheckBox();
        r7 = new javax.swing.JCheckBox();
        r8 = new javax.swing.JCheckBox();
        r9 = new javax.swing.JCheckBox();
        r10 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 17));
        jLabel7.setText("Also check the facilities available ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("The general facilities are available free of cost for every guest.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Wifi available in all areas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Private parking");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Babysitting");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setText("3 - time meal");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel9.setText("Luggage storage");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setText("24 hour front desk");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setText("Below are some particular facilities which are available at nominal rates.");

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("FACILITIES");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("You can choose one or more of these facilities. These facilities are for one time use only.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setText("The charges for these facilities will be added in the final bill.");

        r1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r1.setText("Sauna");

        r3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r3.setText("Massage");

        r2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r2.setText("Fitness Center");

        r4.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r4.setText("Hammam");

        r5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r5.setText("Business Center ");

        r6.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r6.setText("Spa");

        r7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r7.setText("Pool");

        r8.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r8.setText("Meeting/Banquet Facilities");

        r9.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r9.setText("Nightclub/DJ");

        r10.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        r10.setText("Entertainment Staff");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r7)
                        .addContainerGap())
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r1)
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(r2)
                                            .addComponent(r5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(r3)
                                            .addComponent(r6))
                                        .addGap(39, 39, 39))
                                    .addComponent(r8)
                                    .addComponent(r10))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r4)
                        .addContainerGap(507, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r9)
                        .addContainerGap(475, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(27, 27, 27))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13)
                            .addGap(31, 31, 31)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1)
                    .addComponent(r2)
                    .addComponent(r3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r4)
                    .addComponent(r5)
                    .addComponent(r6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r7)
                    .addComponent(r8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r9)
                    .addComponent(r10))
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton2))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel10)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel8)
                    .addGap(46, 46, 46)
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel12)
                    .addGap(5, 5, 5)
                    .addComponent(jLabel13)
                    .addContainerGap(326, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String l = r1.getText();
String l1 = r2.getText();
String l2 = r3.getText();
String l3 = r4.getText();
String l4 = r5.getText();
String l5 = r6.getText();
String l6 = r7.getText();
String l7 = r8.getText();
String l8 = r9.getText();
String l9 = r10.getText();

int s=0;
String u="";
if(r1.isSelected())
{
 u=l;
 int e1=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e1 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=e1;
}
if(r2.isSelected())
{
    u=u+","+l1;
    int e2=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e2 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=s+e2;
}
if(r3.isSelected())
{
    u=u+","+l2;
    int e3=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e3 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=s+e3;
}
if(r4.isSelected())
{
    u=u+","+l3;
    int e4=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e4 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=s+e4;
}
if(r5.isSelected())
{
    u=u+","+l4;
    int e5=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e5 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=s+e5;
}
if(r6.isSelected())
{
    u=u+","+l5;
    int e6=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e6 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=s+e6;
}
if(r7.isSelected())
{
    u=u+","+l6;
    int e7=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e7 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=s+e7;
}
if(r8.isSelected())
{
    u=u+","+l7;
    int e8=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e8 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=s+e8;
}
if(r9.isSelected())
{
    u=u+","+l8;
    int e9=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e9 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=s+e9;
}
if(r10.isSelected())
{
    u=u+","+l9;
    int e10=0;
 try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/management","root","aanchal");
Statement stmt = con.createStatement() ;
String query = "SELECT price from facilities where nof ='"+l+"';";
ResultSet rs = stmt.executeQuery(query) ;
rs.first();
  e10 = rs.getInt("price");
     }
 catch (Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
e.printStackTrace();
 }
 s=s+e10;
}
details h = new details(aaa,iio,iio1,iio2,iio3,iio4,iio5,u,s);
this.setVisible(false);
h.setVisible(true);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
bookroom b = new bookroom();
this.setVisible(false);
b.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox r1;
    private javax.swing.JCheckBox r10;
    private javax.swing.JCheckBox r2;
    private javax.swing.JCheckBox r3;
    private javax.swing.JCheckBox r4;
    private javax.swing.JCheckBox r5;
    private javax.swing.JCheckBox r6;
    private javax.swing.JCheckBox r7;
    private javax.swing.JCheckBox r8;
    private javax.swing.JCheckBox r9;
    // End of variables declaration//GEN-END:variables

}
